name: CI-CD

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test-javascript:

    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      fail-fast: true

      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        node: [ 14, lts/*, current ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Dependencies
        run: npm ci
        working-directory: javascript-solution

      - name: Produce Output
        run: npm start
        working-directory: javascript-solution

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Test
        run: python test

  test-python:

    name: Python ${{ matrix.python }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      fail-fast: true

      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Produce Output
        run: python main.py
        working-directory: python-solution

      - name: Test
        run: python test